### ISSUE TITLE
docsify-ssr

### ISSUE THREAD

**Issue by imohuan** [docsifyjs/docs-zh#14]
### 但是有时候会出现一些莫名其妙的错误
* 好比说在选择侧边栏的时候 会出现点击无效  刷新就没有事情了
* 还有就是 `docsify-cli` 
    * 添加参数的时候报错
     `docsify start . --config './config/ssr.config.js'`
    * 报错: `Unknown argument: ./config/ssr.config.js`    
  
![image](https://user-images.githubusercontent.com/41279222/76694501-7ca8c780-66ae-11ea-9d6d-b62fc41964af.png)

> 这就有些莫名其妙了 不知道如何解决
> 希望官方可以可以帮我解决一下

**Comment by imohuan** [comment]
我希望可以增加 侧边栏和标题的 模板编写

**Comment by imohuan** [comment]
![image](https://fp1.fghrsh.net/2020/03/15/81a5289e1dacce3e434c42bca70b63ed.png)

**Comment by sy-records** [comment]
已在 https://github.com/docsifyjs/docsify-cli/pull/105 中修复，请升级`docsify-cli`
