### ISSUE TITLE
如何生成本地能访问的文件

### ISSUE THREAD

**Issue by lhf-Alice** [docsifyjs/docs-zh#37]
各位大佬，麻烦问下 如何生成本地能访问的。目前打开index 后页面显示空白

**Comment by sy-records** [comment]
直接使用模板 https://github.com/docsifyjs/docsify-template

**Comment by lhf-Alice** [comment]
这个 只能通过部署静态服务器或者本地开启服务器嘛

**Comment by sy-records** [comment]
能访问index.html就可以。

**Comment by lhf-Alice** [comment]
我点击直接打开 index  界面显示空白。是不支持这样的嘛

**Comment by sy-records** [comment]
使用node、python、php、nginx的服务去启动访问index.html
或者安装docsify-cli服务

**Comment by lhf-Alice** [comment]
好的 谢谢哈
