### ISSUE TITLE
各位大佬，有没有可能支持multi-markdown？

### ISSUE THREAD

**Issue by 1human** [docsifyjs/docs-zh#48]
编一个表格太痛苦了，Obsidian有插件能支持multi-markdown，可以很方便的合并单元格。
我前面学着用html写了一个，是可以，但是貌似不支持引用..

**Comment by sy-records** [comment]
目前没计划，在本地编辑的时候使用Typora之类的编辑器，插入表格不是什么问题，至于合并单元格之类的，可以通过css、js实现，或者自己实现一个插件。
