### ISSUE TITLE
自定义背景封面遇到的问题

### ISSUE THREAD

**Issue by Xguihur** [docsifyjs/docs-zh#49]
大佬们我在尝试的时候遇到一个问题请教一下。
我在使用的时候按照指引自定义背景图片为封面时会产生各种问题，只要加了 背景颜色 的那个代码图片就会跑到文字的下方（靠近可视区底部），但是只使用图片的话，图片确实替代了原本的背景封面，但是这个图片被透明化了，这种情况我应该如何解决呢？

**Comment by sy-records** [comment]
需要自己写css进行调整。

**Comment by Xguihur** [comment]
> 需要自己写css进行调整。

好的，感谢！
