### ISSUE TITLE
多页文档的嵌套侧边栏仿佛不起作用

### ISSUE THREAD

**Issue by Buci-1** [docsifyjs/docs-zh#53]
不知道是不是我这边的问题，我在子目录下创建_sidebar.md文件并不起作用

**Comment by toxintoxin** [comment]
我也是，教程是不是过期了

**Comment by sy-records** [comment]
复现问题的repo提供一下

**Comment by toxintoxin** [comment]
> 复现问题的repo提供一下

This repo is for testing, thank you!
<https://github.com/toxintoxin/docsify-nested-sidebar-test.git>

**Comment by sy-records** [comment]
删除这个代码就可以了。

这个的意思是所有的`_sidebar.md`，都从`/_sidebar.md`获取。

```
      alias: {
        '/.*/_sidebar.md': '/_sidebar.md',
      }
```

**Comment by toxintoxin** [comment]
> 删除这个代码就可以了。
> 
> 这个的意思是所有的`_sidebar.md`，都从`/_sidebar.md`获取。
> 
> ```
>       alias: {
>         '/.*/_sidebar.md': '/_sidebar.md',
>       }
> ```

did not work

**Comment by sy-records** [comment]
It works for me, you can clear the cache and retest.
